[2020-07-07 17:15:46.843584] [INFO] 123456
[2020-07-07 17:16:07.747118] [ERROR] 1845151
[2020-07-07 17:18:32.111639] [ERROR] 1845151
[2020-07-07 17:20:22.053629] [WARN] 1845151
[2020-07-07 17:20:48.731750] [DEBUG] 1845151
[2020-07-10 21:37:44.269143] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 192.168.238.131: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[2020-07-11 14:51:14.614028] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 192.168.238.131: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[2020-07-11 14:52:37.677367] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 192.168.238.131: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[2020-07-11 14:53:43.353489] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 192.168.238.131: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[2020-07-11 14:54:35.788278] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 192.168.238.131: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[2020-07-11 14:58:29.575386] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 192.168.238.131: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[2020-07-11 15:05:25.334661] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 192.168.238.131: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
[2020-07-12 11:04:29.499604] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.py[Errno 9] Bad file descriptor
[2020-07-12 11:09:36.250761] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.py[Errno 9] Bad file descriptor
[2020-07-12 11:10:48.645173] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.py[Errno 9] Bad file descriptor
[2020-07-12 11:17:26.295496] [ERROR] E:\python\WWW\mysite\app01\my_tools\corn_ssh.py[Errno 9] Bad file descriptor
[2020-07-12 11:29:25.132419] [ERROR] <class 'paramiko.sftp_attr.SFTPAttributes'>
[2020-08-21 21:11:18.655381] [ERROR] D:\Users\simple\mysite\app01\my_tools\corn_ssh.pyUnable to connect to 127.0.0.1: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
[2020-08-24 21:10:16.700709] [ERROR] delete friend group select_for_update() got an unexpected keyword argument 'is_read'
[2020-08-24 21:14:26.014929] [ERROR] delete friend group cannot unpack non-iterable int object
[2020-08-24 21:17:12.798568] [ERROR] chat_agree_friend cannot unpack non-iterable int object
[2020-08-24 21:26:12.507078] [ERROR] chat_agree_friend FriendGroupFriend() got an unexpected keyword argument 'proposer_id'
[2020-08-24 21:27:45.197068] [ERROR] chat_agree_friend FriendGroupFriend() got an unexpected keyword argument 'proposer_id'
[2020-08-24 21:30:39.670852] [ERROR] chat_agree_friend FriendGroupFriend() got an unexpected keyword argument 'proposer_id'
